---
api_user:  ansible@pam
api_token_id: ansible-token
api_token_secret: "{{ lookup('env', 'PROX_TOKEN_ID') }}"
cloud_init_type: nocloud
node: prox02
task_timeout: 500
clone_source: UBNTUN-24-TEST
clone_source_id: 106 
interface_type: ethernet
interface_name: ens18
gateway: 192.168.101.1
