---
api_user:  ansible@pam
api_token_id: ansible-token
api_token_secret: "{{ lookup('env', 'PROX_TOKEN_ID') }}"
node: prox02
task_timeout: 500
clone_source: UBUNTU-24-TMPLT
clone_source_id: 100
gateway: 192.168.101.1
