---
- name: Deploying VMs
  hosts: prox02
  vars_files:
    - ../group_vars/virtual-machines.yml
  become: false
  gather_facts: false
  vars:
      ansible_python_interpreter: /usr/bin/python3
  roles:
    - roles/create-vm
