#SPDX-License-Identifier: MIT-0
---
# tasks file for reconfigure-vm
- name: Set IP Address
  template:
    src: templates/50-cloud-init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
- name: Set Hostname
  hostname:
    name: "{{ vm_name }}"
